# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntbs', '0002_auto_20171014_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntbook',
            name='meta',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
