# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ntbs', '0003_auto_20171015_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntbook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
