# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntbs', '0004_ntbook_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ntbook',
            old_name='name',
            new_name='snippet',
        ),
    ]
